/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;


import javax.swing.JOptionPane;


/**
 *
 * @author segur
 */


public class AddVehicle extends javax.swing.JFrame {

    /**
     * Creates new form AddVehicle
     */
    private Manager mg;
    //private Menu menu;
    public AddVehicle(Manager mg){
       // this.menu = menu;
        initComponents();
        this.mg=mg;
    }
    
  
    public AddVehicle() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TittleNuevoVehiculo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelBastidor = new javax.swing.JLabel();
        labelMatricula = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelMarca = new javax.swing.JLabel();
        labelModelo = new javax.swing.JLabel();
        labelColor = new javax.swing.JLabel();
        SeleccionadorColor = new javax.swing.JColorChooser();
        labelCombustible = new javax.swing.JLabel();
        labelEtiqueta = new javax.swing.JLabel();
        labelPlazas = new javax.swing.JLabel();
        Desplegablecombustible = new javax.swing.JComboBox<>();
        DesplegableEtiqueta = new javax.swing.JComboBox<>();
        DesplegableMarca = new javax.swing.JComboBox<>();
        Textobastidor = new javax.swing.JTextField();
        Textomatricula = new javax.swing.JTextField();
        TextoModelo = new javax.swing.JTextField();
        TextoPlazas = new javax.swing.JTextField();
        bMenu = new javax.swing.JButton();
        bCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TittleNuevoVehiculo.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        TittleNuevoVehiculo.setText("Nuevo Vehiculo");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        labelBastidor.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        labelBastidor.setText("Numero Bastidor");

        labelMatricula.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        labelMatricula.setText("Matricula");

        labelMarca.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        labelMarca.setText("Marca");

        labelModelo.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        labelModelo.setText("Modelo");

        labelColor.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        labelColor.setText("Color");

        labelCombustible.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        labelCombustible.setText("Combustible");

        labelEtiqueta.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        labelEtiqueta.setText("Etiqueta");

        labelPlazas.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        labelPlazas.setText("Num. Plazas");

        Desplegablecombustible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Diesel", "Electrico", "Hibrido" }));
        Desplegablecombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesplegablecombustibleActionPerformed(evt);
            }
        });

        DesplegableEtiqueta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etiqueta B", "Etiqueta C", "Etiqueta ECO", "Etiqueta 0" }));

        DesplegableMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alfa Romeo", "Audi", "BMW", "Citroen", "Fiat", "Honda", "Mercedes", "Opel", "Renault", "Seat", "Toyota", "Volkswagen", "Volvo", "Hyundai", "Peugeot", "Ford", "Lexus", "Mazda", "Mitsubishi", "Subaru", "Abarath", "Mini", "Ds", "Suzuki", "Smart", "Dacia", "Jaguar", "Maseratti", "Porsche", "Aston Martin", "Bentley", "Byd", "Jeep", "Land Rover", "Tesla", "Skoda", "MG", "Cupra", "Nissan", "Kia", "Omoda", "Ferrari", "Lamborghini" }));

        TextoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoModeloActionPerformed(evt);
            }
        });

        bMenu.setText("Menu");
        bMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuActionPerformed(evt);
            }
        });

        bCrear.setText("Crear");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelBastidor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Textobastidor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(labelModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(Textomatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TextoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(DesplegableMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(bCrear)
                                                    .addComponent(SeleccionadorColor, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(24, 24, 24)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(labelPlazas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labelCombustible, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(labelEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(DesplegableEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Desplegablecombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(TextoPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(bMenu)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(TittleNuevoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(TittleNuevoVehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBastidor)
                    .addComponent(Textobastidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatricula)
                    .addComponent(Textomatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMarca)
                    .addComponent(DesplegableMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModelo)
                    .addComponent(TextoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelColor)
                    .addComponent(SeleccionadorColor, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCombustible)
                    .addComponent(Desplegablecombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEtiqueta)
                    .addComponent(DesplegableEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPlazas)
                    .addComponent(TextoPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bMenu)
                    .addComponent(bCrear))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoModeloActionPerformed

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        // TODO add your handling code here:  
        Vehicle ve = new Vehicle();
        Textobastidor.setText(String.valueOf(ve.getNumeroBastidor()));
        ve.setMatricula(Textomatricula.getText());
        ve.setMarca((String) DesplegableMarca.getSelectedItem());
        ve.setModelo(TextoModelo.getText());
        ve.setColor((String) SeleccionadorColor.getColor().toString());
        ve.setCombustible((String) Desplegablecombustible.getSelectedItem());
        ve.setEtiqueta((String) DesplegableEtiqueta.getSelectedItem());
        TextoPlazas.setText(String.valueOf(ve.getnPlazas()));
        try{
            mg.addVehicle(ve);
        }
        catch(Exception e){
            e.getMessage();
        }
        
        JOptionPane.showMessageDialog(null, "Vehiculo registrado con Matricula "+ve.getMatricula(), "Success", JOptionPane.INFORMATION_MESSAGE);
        
       
       



        
    }//GEN-LAST:event_bCrearActionPerformed

    private void DesplegablecombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesplegablecombustibleActionPerformed

    }//GEN-LAST:event_DesplegablecombustibleActionPerformed

    private void bMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuActionPerformed
        Menu menu = new Menu(mg);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bMenuActionPerformed
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DesplegableEtiqueta;
    private javax.swing.JComboBox<String> DesplegableMarca;
    private javax.swing.JComboBox<String> Desplegablecombustible;
    private javax.swing.JColorChooser SeleccionadorColor;
    private javax.swing.JTextField TextoModelo;
    private javax.swing.JTextField TextoPlazas;
    private javax.swing.JTextField Textobastidor;
    private javax.swing.JTextField Textomatricula;
    private javax.swing.JLabel TittleNuevoVehiculo;
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bMenu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBastidor;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelCombustible;
    private javax.swing.JLabel labelEtiqueta;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelModelo;
    private javax.swing.JLabel labelPlazas;
    // End of variables declaration//GEN-END:variables
}
