/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author segur
 */
public class Menu extends javax.swing.JFrame {

    Manager mg= new Manager();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        MySQL ms = new MySQL();
        ArrayList vehicles =ms.getVehicles();
        mg.setVehicles(vehicles);
    }
    
     public Menu(Manager mg) {
        initComponents();
        this.mg=mg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleMenu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bAddVehicle = new javax.swing.JButton();
        bImportDatos = new javax.swing.JButton();
        bSerachMatricula = new javax.swing.JButton();
        bExportDatos = new javax.swing.JButton();
        bDeleteVehicle = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        bModify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleMenu.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        TitleMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TitleMenu.setLabelFor(TitleMenu);
        TitleMenu.setText("Menu");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        bAddVehicle.setText("Nuevo Vehiculo");
        bAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddVehicleActionPerformed(evt);
            }
        });

        bImportDatos.setText("Importar Datos");
        bImportDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImportDatosActionPerformed(evt);
            }
        });

        bSerachMatricula.setText("Buscar Matricula");
        bSerachMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSerachMatriculaActionPerformed(evt);
            }
        });

        bExportDatos.setText("Exportar Datos");
        bExportDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExportDatosActionPerformed(evt);
            }
        });

        bDeleteVehicle.setText("Eliminar Vehiculo");
        bDeleteVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteVehicleActionPerformed(evt);
            }
        });

        bExit.setText("Salir");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        bModify.setText("Modificar Informacion");
        bModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bImportDatos)
                    .addComponent(bDeleteVehicle)
                    .addComponent(bModify)
                    .addComponent(bAddVehicle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bExportDatos)
                    .addComponent(bSerachMatricula)
                    .addComponent(bExit))
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(TitleMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddVehicle)
                    .addComponent(bSerachMatricula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bImportDatos)
                    .addComponent(bExportDatos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDeleteVehicle)
                    .addComponent(bExit))
                .addGap(18, 18, 18)
                .addComponent(bModify)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddVehicleActionPerformed
        AddVehicle  addVehicle = new AddVehicle(mg);
        addVehicle.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bAddVehicleActionPerformed

    private void bSerachMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSerachMatriculaActionPerformed
        SearchInfo search = new SearchInfo(mg);
        search.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bSerachMatriculaActionPerformed

    private void bDeleteVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteVehicleActionPerformed
       DeleteVehicle delVeh = new DeleteVehicle(mg);
       delVeh.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_bDeleteVehicleActionPerformed

    private void bModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModifyActionPerformed
        ModifyInfo update = new ModifyInfo(mg);
        update.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bModifyActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bExitActionPerformed

    private void bImportDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImportDatosActionPerformed
        Import datos = new Import(mg);
        datos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bImportDatosActionPerformed

    private void bExportDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExportDatosActionPerformed
            try {
             mg.exportData();
             JOptionPane.showMessageDialog(this, "Se ha generado un archivo SQL en Descargas de tu PC", "Éxito", JOptionPane.INFORMATION_MESSAGE);
         } catch (IOException e) {
             e.printStackTrace();
             JOptionPane.showMessageDialog(this, "Error al exportar datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_bExportDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleMenu;
    private javax.swing.JButton bAddVehicle;
    private javax.swing.JButton bDeleteVehicle;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bExportDatos;
    private javax.swing.JButton bImportDatos;
    private javax.swing.JButton bModify;
    private javax.swing.JButton bSerachMatricula;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
